"""add_onboarding_fields_to_users

Revision ID: 5eff9d6355d1
Revises: a3f2b1c0d9e8
Create Date: 2026-05-18 20:29:43.889306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5eff9d6355d1'
down_revision: Union[str, Sequence[str], None] = 'a3f2b1c0d9e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('coding_experience', sa.String(), nullable=True))
    op.add_column('users', sa.Column('learning_goal', sa.String(), nullable=True))
    op.add_column('users', sa.Column('interested_topics', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'interested_topics')
    op.drop_column('users', 'learning_goal')
    op.drop_column('users', 'coding_experience')
    # ### end Alembic commands ###
